on:
  workflow_dispatch:
  schedule:
  - cron: 0 4 * * 0 # Every Sunday at 4am

name: Update Azure Regions JSON
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - uses: actions/checkout@v4

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # add action that calls an Azure CLI command
    - uses: azure/CLI@v1
      with:
        inlineScript: |
          az account list-locations --query "[].{displayName:displayName, name:name, latitude:metadata.latitude, longitude:metadata.longitude}" --output json > azure-regions/azure_regions.json

    - name: Commit and Push Changes
      if: steps.check_changes.outputs.has_changes == 'true'
      run: |
        git config --global user.email "${{ github.actor }}"
        git config --global user.name "${{ github.actor }}@users.noreply.github.com"

        git add azure-regions/azure_regions.json
        git commit -m 'Update Azure regions json'

        git push
