on:
  workflow_dispatch:
  schedule:
  - cron: 0 0 * * 3 # Every Wednesday

name: Update Azure Regions JSON
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # add action that calls an Azure CLI command
    - uses: azure/CLI@v1
      with:
        inlineScript: |
          az account list-locations --query "[].{displayName:displayName, name:name, latitude:metadata.latitude, longitude:metadata.longitude}" --output json > ./azure-regions/azure_regions.json

    # add action that commits local changes back to repo
    - uses: actions/commit@v1
      with:
        # commit message
        message: 'Update Azure Regions'
        # files to commit
        files: ./azure-regions/azure_regions.json
        # name of branch to commit to
        branch: main
        # name of author
        author_name: GitHub Actions
        # email of author
        #author_email: